project_id = "vcbyxscfoitmcjrjtjtd"

[functions.lesson-planner]
verify_jwt = false

[functions.visual-aid-design]
verify_jwt = false

[functions.quiz-generator]
verify_jwt = false

[functions.worksheet-generator]
verify_jwt = false

[functions.question-paper]
verify_jwt = false
