import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { useToast } from '@/hooks/use-toast';
import { CLASSES, MEDIUMS, DEFAULT_SUBJECTS } from '@/types/student';
import { UserPlus, Loader2 } from 'lucide-react';

export function StudentForm() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    name: '',
    class: '',
    age: '',
    gender: '',
    parent_guardian_name: '',
    village: '',
    medium_of_instruction: '',
    subjects: [] as string[],
  });

  const handleSubjectToggle = (subject: string) => {
    setFormData((prev) => ({
      ...prev,
      subjects: prev.subjects.includes(subject)
        ? prev.subjects.filter((s) => s !== subject)
        : [...prev.subjects, subject],
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.name || !formData.class || !formData.age || !formData.gender || 
        !formData.parent_guardian_name || !formData.village || !formData.medium_of_instruction ||
        formData.subjects.length === 0) {
      toast({
        title: 'Missing Information',
        description: 'Please fill in all required fields.',
        variant: 'destructive',
      });
      return;
    }

    setLoading(true);

    try {
      const { data, error } = await supabase
        .from('students')
        .insert({
          name: formData.name,
          class: formData.class,
          age: parseInt(formData.age),
          gender: formData.gender,
          parent_guardian_name: formData.parent_guardian_name,
          village: formData.village,
          medium_of_instruction: formData.medium_of_instruction,
          subjects: formData.subjects,
          student_id: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Student Admitted Successfully!',
        description: `${formData.name} has been registered with ID: ${data.student_id}`,
      });

      navigate(`/students/${data.id}`);
    } catch (error: any) {
      toast({
        title: 'Error',
        description: error.message || 'Failed to add student.',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-8">
      {/* Basic Information */}
      <div className="card-elevated p-6">
        <h3 className="section-title">Basic Information</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="name">Student Name *</Label>
            <Input
              id="name"
              placeholder="Enter full name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              className="input-field"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="class">Class / Grade *</Label>
            <Select
              value={formData.class}
              onValueChange={(value) => setFormData({ ...formData, class: value })}
            >
              <SelectTrigger className="input-field">
                <SelectValue placeholder="Select class" />
              </SelectTrigger>
              <SelectContent>
                {CLASSES.map((cls) => (
                  <SelectItem key={cls} value={cls}>
                    Class {cls}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="age">Age *</Label>
            <Input
              id="age"
              type="number"
              min="3"
              max="25"
              placeholder="Enter age"
              value={formData.age}
              onChange={(e) => setFormData({ ...formData, age: e.target.value })}
              className="input-field"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="gender">Gender *</Label>
            <Select
              value={formData.gender}
              onValueChange={(value) => setFormData({ ...formData, gender: value })}
            >
              <SelectTrigger className="input-field">
                <SelectValue placeholder="Select gender" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="Male">Male</SelectItem>
                <SelectItem value="Female">Female</SelectItem>
                <SelectItem value="Other">Other</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
      </div>

      {/* Guardian & Location */}
      <div className="card-elevated p-6">
        <h3 className="section-title">Guardian & Location</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-2">
            <Label htmlFor="parent">Parent / Guardian Name *</Label>
            <Input
              id="parent"
              placeholder="Enter guardian's name"
              value={formData.parent_guardian_name}
              onChange={(e) => setFormData({ ...formData, parent_guardian_name: e.target.value })}
              className="input-field"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="village">Village *</Label>
            <Input
              id="village"
              placeholder="Enter village name"
              value={formData.village}
              onChange={(e) => setFormData({ ...formData, village: e.target.value })}
              className="input-field"
            />
          </div>
        </div>
      </div>

      {/* Academic Details */}
      <div className="card-elevated p-6">
        <h3 className="section-title">Academic Details</h3>
        
        <div className="space-y-2 mb-6">
          <Label htmlFor="medium">Medium of Instruction *</Label>
          <Select
            value={formData.medium_of_instruction}
            onValueChange={(value) => setFormData({ ...formData, medium_of_instruction: value })}
          >
            <SelectTrigger className="input-field max-w-md">
              <SelectValue placeholder="Select medium" />
            </SelectTrigger>
            <SelectContent>
              {MEDIUMS.map((medium) => (
                <SelectItem key={medium} value={medium}>
                  {medium}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="space-y-3">
          <Label>Subjects * (Select all that apply)</Label>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {DEFAULT_SUBJECTS.map((subject) => (
              <div
                key={subject}
                className="flex items-center space-x-2 p-3 rounded-lg border border-border hover:bg-muted/50 transition-colors"
              >
                <Checkbox
                  id={subject}
                  checked={formData.subjects.includes(subject)}
                  onCheckedChange={() => handleSubjectToggle(subject)}
                />
                <label
                  htmlFor={subject}
                  className="text-sm font-medium cursor-pointer"
                >
                  {subject}
                </label>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Submit Button */}
      <div className="flex justify-end gap-4">
        <Button
          type="button"
          variant="outline"
          onClick={() => navigate('/students')}
        >
          Cancel
        </Button>
        <Button
          type="submit"
          disabled={loading}
          className="btn-primary-gradient px-8"
        >
          {loading ? (
            <>
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Registering...
            </>
          ) : (
            <>
              <UserPlus className="mr-2 h-4 w-4" />
              Register Student
            </>
          )}
        </Button>
      </div>
    </form>
  );
}
